# Dependencies
markdown:         redcarpet
highlighter:      pygments


# Setup
title:            Glasgow Children Hospital (GCH) Minecraft
tagline:          'A Jekyll theme'
description:      'Documentation of making GCH in minecraft'
url:              http://hadi.link/gch_minecraft
baseurl:          /

author:
  name:           'Hadi Mehrpouya'
  url:            http://hadi.link

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/Mehrpouya/gch_minecraft/
